OD-111 [Task] Grammatical number message correct spelling for delete forever action
Fliplet/fliplet-widget-file-manager pull request #71
Opened 2021-01-28 10:42 UTC by ivandevupp

@sofiiakvasnevska
## Issue
OD-111 https://weboo.atlassian.net/browse/OD-111
## Description
Grammatical number message correct spelling for delete forever action
## Screenshots/screencasts
https://monosnap.com/file/PGnQclpDohB5To3ikcWmmF9xlnDR3V
## Backward compatibility
This change is fully backward compatible.
## Reviewers 
@upplabs-alex-levchenko @AndrRyaz

2021-01-29 18:28 UTC, tonytlwu requested changes

2021-01-29 18:28 UTC, tonytlwu commented on js/interface.js
> +        + ($items.length > 1 ? 'files' : 'the file')
```suggestion
        + ($items.length > 1 ? $items.length + ' files' : 'the file')
```

2021-01-29 18:28 UTC, tonytlwu commented on js/interface.js
> +        + ($items.length > 1 ? 'files' : 'the file')
```suggestion
        + ($items.length > 1 ? $items.length + ' files' : 'the file')
```

2021-02-01 11:08 UTC, ivandevupp commented on js/interface.js
> +        + ($items.length > 1 ? 'files' : 'the file')
Fixed.

2021-02-01 11:08 UTC, ivandevupp commented on js/interface.js
> +        + ($items.length > 1 ? 'files' : 'the file')
Fixed.

2021-02-03 10:01 UTC, tonytlwu approved these changes
@sofiiakvasnevska This is ready for testing

Risk: Low
Affected: Studio users deleting files in Studio
Verify:  File deleting is working correctly

Squash and merge: Use PR title

2021-02-03 10:23 UTC, merged